// Module API tests

// If you had any hopes: This is a token from a development machine.
@token = 55D037C736E576F2A3B27904ACC1E443

// Module prefix
@prefix = em_api_demo
// Delimiter can be: comma, semicolon, tab, space, caret, pipe
@delim = comma
// Format and return format can be: json, csv, xml
@format = json
@returnFormat = json


### Test: Add an item
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&token={{token}}
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=add-item
&item-name=My first item!

### Test: Get an item
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&token={{token}}
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=get-item
&item-id=6f1f50e8-8f3e-4d6c-a005-3c1c993bc519

### Test: List items
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&token={{token}}
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=list-items

### Test: Remove an item
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&token={{token}}
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=remove-item
&item-id=6f1f50e8-8f3e-4d6c-a005-3c1c993bc519
