// Module API tests

// If you had any hopes: This is a token from a development machine.
@token = 55D037C736E576F2A3B27904ACC1E443

// Module prefix
@prefix = em_api_demo
// Delimiter can be: comma, semicolon, tab, space, caret, pipe
@delim = comma
// Format and return format can be: json, csv, xml
@format = json
@returnFormat = json


### Test: Add an item
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&token={{token}}
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=add-item
&item-name=My first item!

### Test: Get an item
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&token={{token}}
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=get-item
&item-id=f3ad3527-0446-49b5-9acd-b5a25d19cf7a

### Test: List items
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&token={{token}}
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=list-items

### Test: Remove an item
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&token={{token}}
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=remove-item
&item-id=27b931c6-033f-477b-ade6-e1c89cee8061

// No-auth

### Test: List items (without authenticating)
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=list-items


### Test: Get an item (without authenticating)
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=get-item
&item-id=c690b708-9643-428f-a61d-289d2ba36eb2

### Test: Remove an item (without authenticating - not possible)
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=remove-item
&item-id=3fb8620f-6508-403b-a384-08e638ff1c70

### Test: Add an item (no-auth)
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=add-item
&item-name=Item without project scope!



### Special action
POST https://dev-redcap/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

content=externalModule
&token={{token}}
&prefix={{prefix}}
&format={{format}}
&returnFormat={{returnFormat}}
&csvDelim={{delim}}
&action=__info
